(
    # this makes sure the script is run in the directory of where its placed
    cd "$(dirname "$0")" || exit 1

    # combine the compile commands generated by cmake so the intellisens is applied to both projects simultaniusly
    jq -s '.[0] + .[1]' build_m7/compile_commands.json build_m4/compile_commands.json > out/combined_compile_commands.json
)